In [17]:
import numpy as np
import pandas as pd

In [18]:
# Create a 1D array from 1 to 10
original_array = np.arange(1,11)

# Reshape into a 2x5 matrix
matrix_2x5 = original_array.reshape(2,5)

print(matrix_2x5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
# Create a 1D array from 1 to 20
arr = np.arange(1,21)

# Extract elements between the 5th and 15th index
# This excludes the 15th index itself
sliced_arr = arr[5:15]

print("Original Array:", arr)
print("Extracted Slice:", sliced_arr)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Extracted Slice: [ 6  7  8  9 10 11 12 13 14 15]


In [20]:
# Recreating the array from 1 to 20
arr = np.arange(1,21)

# Compute statistics
mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)

print(f"Mean: {mean_val}")
print(f"Median: {median_val}")
print(f"Standard Deviation: {std_val:.2f}")

Mean: 10.5
Median: 10.5
Standard Deviation: 5.77


In [21]:
# Create a 2D array x of shape(3,4)
x = np.array([[10,20,30,40],
              [50,60,70,80],
              [90,100,110,120]])

# Create a 2D array x of shape(4,)
y = np.array([1,2,3,4])


# Subtract y from each row of x using broadcasting
result = x - y

print("Array x:\n", x)
print("\nArray y:\n", y)
print("\nResult after broadcasting:\n", result)



Array x:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Array y:
 [1 2 3 4]

Result after broadcasting:
 [[  9  18  27  36]
 [ 49  58  67  76]
 [ 89  98 107 116]]


In [22]:
# --- Step 1: Create the initial DataFrame with 10 rows ---
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'age':[25, 35, 30, 22, 50, 37, 27, 57, 32, 45],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male']
}
df = pd.DataFrame(data)

# --- Step 2: Add the 'occupation' column ---
# We use a list that repeats 'Programmer', 'Manager', and 'Analyst' to fill the 10 rows
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['occupation'] = occupations

# --- Step 3: Select rows where age is greater than or equal to 30 ---
filtered_df = df[df['age'] >= 30]

# --- Step 4: Convert to CSV, read it back, and display the contents ---
# Save to a local CSV file
df.to_csv('people_data.csv', index=False)

# Read the CSV file back into a new DataFrame
loaded_df = pd.read_csv('people_data.csv')

# --- Displaying the Outputs ---
print("--- 1 & 2) Full DataFrame with Occupation Added ---")
print(df)

print("\n--- 3) Rows where Age >= 30 ---")
print(filtered_df)

print("\n--- 4) Contents Displayed After Reading from CSV ---")
print(loaded_df)

--- 1 & 2) Full DataFrame with Occupation Added ---
      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   35    Male     Manager
2  Charlie   30    Male     Analyst
3    David   22    Male  Programmer
4      Eva   50  Female     Manager
5    Frank   37    Male     Analyst
6    Grace   27  Female  Programmer
7    Henry   57    Male     Manager
8      Ivy   32  Female     Analyst
9     Jack   45    Male  Programmer

--- 3) Rows where Age >= 30 ---
      name  age  gender  occupation
1      Bob   35    Male     Manager
2  Charlie   30    Male     Analyst
4      Eva   50  Female     Manager
5    Frank   37    Male     Analyst
7    Henry   57    Male     Manager
8      Ivy   32  Female     Analyst
9     Jack   45    Male  Programmer

--- 4) Contents Displayed After Reading from CSV ---
      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   35    Male     Manager
2  Charlie   30    Male     Analyst
3    David   22    Male  Programm